using NUnit.Framework;
using SkiaSharp;
using System.Collections;
using System.Collections.Generic;

namespace Notadesigner.Shades.Tests
{
    [TestFixture]
    public class ShadeTests
    {
        [TestCaseSource(typeof(TestDataSources), nameof(TestDataSources.ApplyTransparencyData))]
        public SKColor ApplyTransparencyTest(SKBitmap canvas, SKColor applied)
        {
            var instance = new BlockShade(new SKColor(0, 0, 0));
            var result = instance.ApplyTransparency(new SKPointI(0, 0), canvas, applied);

            return result;
        }

        [TestCaseSource(typeof(TestDataSources), nameof(TestDataSources.AdjustPointData))]
        public void AdjustPointTest(SKPoint point, int warpSize, float scale, long seed, SKPoint expected)
        {
            var instance = new BlockShade(new SKColor(0, 0, 0, 255), warpSize);
            instance.WarpNoises[0] = new NoiseField(scale, seed);
            instance.WarpNoises[1] = new NoiseField(scale, seed);

            var result = instance.AdjustPoint(point);

            Assert.That(result.X, Is.EqualTo(expected.X).Within(0.1));
            Assert.That(result.Y, Is.EqualTo(expected.Y).Within(0.1));
        }

        [TestCaseSource(typeof(TestDataSources), nameof(TestDataSources.GetShapeEdgeData))]
        public void GetShapeEdgeTest(IList<SKPoint> edgePoints, Queue<SKPoint> expected, int testIndex)
        {
            var instance = new BlockShade(new SKColor(255, 0, 0, 127), 0);

            var result = instance.GetShapeEdge(edgePoints);

            foreach (var point in result)
            {
                var p = expected.Peek();
                if (p.X == point.X && p.Y == point.Y)
                {
                    p = expected.Dequeue();
                }
            }

            Assert.AreEqual(0, expected.Count);
        }

        [TestCaseSource(nameof(PixelsInsideEdgeTestSource))]
        public void PixelsInsideEdgeTest(float radius, IEnumerable<SKPoint> expected)
        {
            var instance = new BlockShade(new SKColor(0, 0, 0, 128));
            var edges = instance.GetCircleEdge(new SKPoint(0, 0), radius);
            var pixels = instance.PixelsInsideEdgeSlow(edges);

            CollectionAssert.AreEqual(expected, pixels);
        }

        [TestCaseSource(nameof(PixelsInsideEdgeTestSource))]
        public void PixelsInsideEdgeFastTest(float radius, IEnumerable<SKPoint> expected)
        {
            var instance = new BlockShade(new SKColor(0, 0, 0, 128));
            var edges = instance.GetCircleEdge(new SKPoint(0, 0), radius);
            var pixels = instance.PixelsInsideEdge(edges);

            CollectionAssert.AreEqual(expected, pixels);
        }

        private static IEnumerable PixelsInsideEdgeTestSource()
        {
            var expected = new SKPoint[]
            {
                new SKPoint() {X=-10f, Y=-3f},
                new SKPoint() {X=-9f, Y=-4f},
                new SKPoint() {X=-9f, Y=-3f},
                new SKPoint() {X=-9f, Y=-2f},
                new SKPoint() {X=-9f, Y=-1f},
                new SKPoint() {X=-9f, Y=0f},
                new SKPoint() {X=-9f, Y=1f},
                new SKPoint() {X=-9f, Y=2f},
                new SKPoint() {X=-8f, Y=-6f},
                new SKPoint() {X=-8f, Y=-5f},
                new SKPoint() {X=-8f, Y=-4f},
                new SKPoint() {X=-8f, Y=-3f},
                new SKPoint() {X=-8f, Y=-2f},
                new SKPoint() {X=-8f, Y=-1f},
                new SKPoint() {X=-8f, Y=0f},
                new SKPoint() {X=-8f, Y=1f},
                new SKPoint() {X=-8f, Y=2f},
                new SKPoint() {X=-8f, Y=3f},
                new SKPoint() {X=-8f, Y=4f},
                new SKPoint() {X=-8f, Y=5f},
                new SKPoint() {X=-7f, Y=-8f},
                new SKPoint() {X=-7f, Y=-7f},
                new SKPoint() {X=-7f, Y=-6f},
                new SKPoint() {X=-7f, Y=-5f},
                new SKPoint() {X=-7f, Y=-4f},
                new SKPoint() {X=-7f, Y=-3f},
                new SKPoint() {X=-7f, Y=-2f},
                new SKPoint() {X=-7f, Y=-1f},
                new SKPoint() {X=-7f, Y=0f},
                new SKPoint() {X=-7f, Y=1f},
                new SKPoint() {X=-7f, Y=2f},
                new SKPoint() {X=-7f, Y=3f},
                new SKPoint() {X=-7f, Y=4f},
                new SKPoint() {X=-7f, Y=5f},
                new SKPoint() {X=-7f, Y=6f},
                new SKPoint() {X=-6f, Y=-8f},
                new SKPoint() {X=-6f, Y=-7f},
                new SKPoint() {X=-6f, Y=-6f},
                new SKPoint() {X=-6f, Y=-5f},
                new SKPoint() {X=-6f, Y=-4f},
                new SKPoint() {X=-6f, Y=-3f},
                new SKPoint() {X=-6f, Y=-2f},
                new SKPoint() {X=-6f, Y=-1f},
                new SKPoint() {X=-6f, Y=0f},
                new SKPoint() {X=-6f, Y=1f},
                new SKPoint() {X=-6f, Y=2f},
                new SKPoint() {X=-6f, Y=3f},
                new SKPoint() {X=-6f, Y=4f},
                new SKPoint() {X=-6f, Y=5f},
                new SKPoint() {X=-6f, Y=6f},
                new SKPoint() {X=-6f, Y=7f},
                new SKPoint() {X=-5f, Y=-9f},
                new SKPoint() {X=-5f, Y=-8f},
                new SKPoint() {X=-5f, Y=-7f},
                new SKPoint() {X=-5f, Y=-6f},
                new SKPoint() {X=-5f, Y=-5f},
                new SKPoint() {X=-5f, Y=-4f},
                new SKPoint() {X=-5f, Y=-3f},
                new SKPoint() {X=-5f, Y=-2f},
                new SKPoint() {X=-5f, Y=-1f},
                new SKPoint() {X=-5f, Y=0f},
                new SKPoint() {X=-5f, Y=1f},
                new SKPoint() {X=-5f, Y=2f},
                new SKPoint() {X=-5f, Y=3f},
                new SKPoint() {X=-5f, Y=4f},
                new SKPoint() {X=-5f, Y=5f},
                new SKPoint() {X=-5f, Y=6f},
                new SKPoint() {X=-5f, Y=7f},
                new SKPoint() {X=-5f, Y=8f},
                new SKPoint() {X=-4f, Y=-9f},
                new SKPoint() {X=-4f, Y=-8f},
                new SKPoint() {X=-4f, Y=-7f},
                new SKPoint() {X=-4f, Y=-6f},
                new SKPoint() {X=-4f, Y=-5f},
                new SKPoint() {X=-4f, Y=-4f},
                new SKPoint() {X=-4f, Y=-3f},
                new SKPoint() {X=-4f, Y=-2f},
                new SKPoint() {X=-4f, Y=-1f},
                new SKPoint() {X=-4f, Y=0f},
                new SKPoint() {X=-4f, Y=1f},
                new SKPoint() {X=-4f, Y=2f},
                new SKPoint() {X=-4f, Y=3f},
                new SKPoint() {X=-4f, Y=4f},
                new SKPoint() {X=-4f, Y=5f},
                new SKPoint() {X=-4f, Y=6f},
                new SKPoint() {X=-4f, Y=7f},
                new SKPoint() {X=-4f, Y=8f},
                new SKPoint() {X=-3f, Y=-10f},
                new SKPoint() {X=-3f, Y=-9f},
                new SKPoint() {X=-3f, Y=-8f},
                new SKPoint() {X=-3f, Y=-7f},
                new SKPoint() {X=-3f, Y=-6f},
                new SKPoint() {X=-3f, Y=-5f},
                new SKPoint() {X=-3f, Y=-4f},
                new SKPoint() {X=-3f, Y=-3f},
                new SKPoint() {X=-3f, Y=-2f},
                new SKPoint() {X=-3f, Y=-1f},
                new SKPoint() {X=-3f, Y=0f},
                new SKPoint() {X=-3f, Y=1f},
                new SKPoint() {X=-3f, Y=2f},
                new SKPoint() {X=-3f, Y=3f},
                new SKPoint() {X=-3f, Y=4f},
                new SKPoint() {X=-3f, Y=5f},
                new SKPoint() {X=-3f, Y=6f},
                new SKPoint() {X=-3f, Y=7f},
                new SKPoint() {X=-3f, Y=8f},
                new SKPoint() {X=-2f, Y=-10f},
                new SKPoint() {X=-2f, Y=-9f},
                new SKPoint() {X=-2f, Y=-8f},
                new SKPoint() {X=-2f, Y=-7f},
                new SKPoint() {X=-2f, Y=-6f},
                new SKPoint() {X=-2f, Y=-5f},
                new SKPoint() {X=-2f, Y=-4f},
                new SKPoint() {X=-2f, Y=-3f},
                new SKPoint() {X=-2f, Y=-2f},
                new SKPoint() {X=-2f, Y=-1f},
                new SKPoint() {X=-2f, Y=0f},
                new SKPoint() {X=-2f, Y=1f},
                new SKPoint() {X=-2f, Y=2f},
                new SKPoint() {X=-2f, Y=3f},
                new SKPoint() {X=-2f, Y=4f},
                new SKPoint() {X=-2f, Y=5f},
                new SKPoint() {X=-2f, Y=6f},
                new SKPoint() {X=-2f, Y=7f},
                new SKPoint() {X=-2f, Y=8f},
                new SKPoint() {X=-2f, Y=9f},
                new SKPoint() {X=-1f, Y=-10f},
                new SKPoint() {X=-1f, Y=-9f},
                new SKPoint() {X=-1f, Y=-8f},
                new SKPoint() {X=-1f, Y=-7f},
                new SKPoint() {X=-1f, Y=-6f},
                new SKPoint() {X=-1f, Y=-5f},
                new SKPoint() {X=-1f, Y=-4f},
                new SKPoint() {X=-1f, Y=-3f},
                new SKPoint() {X=-1f, Y=-2f},
                new SKPoint() {X=-1f, Y=-1f},
                new SKPoint() {X=-1f, Y=0f},
                new SKPoint() {X=-1f, Y=1f},
                new SKPoint() {X=-1f, Y=2f},
                new SKPoint() {X=-1f, Y=3f},
                new SKPoint() {X=-1f, Y=4f},
                new SKPoint() {X=-1f, Y=5f},
                new SKPoint() {X=-1f, Y=6f},
                new SKPoint() {X=-1f, Y=7f},
                new SKPoint() {X=-1f, Y=8f},
                new SKPoint() {X=-1f, Y=9f},
                new SKPoint() {X=0f, Y=-10f},
                new SKPoint() {X=0f, Y=-9f},
                new SKPoint() {X=0f, Y=-8f},
                new SKPoint() {X=0f, Y=-7f},
                new SKPoint() {X=0f, Y=-6f},
                new SKPoint() {X=0f, Y=-5f},
                new SKPoint() {X=0f, Y=-4f},
                new SKPoint() {X=0f, Y=-3f},
                new SKPoint() {X=0f, Y=-2f},
                new SKPoint() {X=0f, Y=-1f},
                new SKPoint() {X=0f, Y=0f},
                new SKPoint() {X=0f, Y=1f},
                new SKPoint() {X=0f, Y=2f},
                new SKPoint() {X=0f, Y=3f},
                new SKPoint() {X=0f, Y=4f},
                new SKPoint() {X=0f, Y=5f},
                new SKPoint() {X=0f, Y=6f},
                new SKPoint() {X=0f, Y=7f},
                new SKPoint() {X=0f, Y=8f},
                new SKPoint() {X=0f, Y=9f},
                new SKPoint() {X=1f, Y=-10f},
                new SKPoint() {X=1f, Y=-9f},
                new SKPoint() {X=1f, Y=-8f},
                new SKPoint() {X=1f, Y=-7f},
                new SKPoint() {X=1f, Y=-6f},
                new SKPoint() {X=1f, Y=-5f},
                new SKPoint() {X=1f, Y=-4f},
                new SKPoint() {X=1f, Y=-3f},
                new SKPoint() {X=1f, Y=-2f},
                new SKPoint() {X=1f, Y=-1f},
                new SKPoint() {X=1f, Y=0f},
                new SKPoint() {X=1f, Y=1f},
                new SKPoint() {X=1f, Y=2f},
                new SKPoint() {X=1f, Y=3f},
                new SKPoint() {X=1f, Y=4f},
                new SKPoint() {X=1f, Y=5f},
                new SKPoint() {X=1f, Y=6f},
                new SKPoint() {X=1f, Y=7f},
                new SKPoint() {X=1f, Y=8f},
                new SKPoint() {X=1f, Y=9f},
                new SKPoint() {X=2f, Y=-10f},
                new SKPoint() {X=2f, Y=-9f},
                new SKPoint() {X=2f, Y=-8f},
                new SKPoint() {X=2f, Y=-7f},
                new SKPoint() {X=2f, Y=-6f},
                new SKPoint() {X=2f, Y=-5f},
                new SKPoint() {X=2f, Y=-4f},
                new SKPoint() {X=2f, Y=-3f},
                new SKPoint() {X=2f, Y=-2f},
                new SKPoint() {X=2f, Y=-1f},
                new SKPoint() {X=2f, Y=0f},
                new SKPoint() {X=2f, Y=1f},
                new SKPoint() {X=2f, Y=2f},
                new SKPoint() {X=2f, Y=3f},
                new SKPoint() {X=2f, Y=4f},
                new SKPoint() {X=2f, Y=5f},
                new SKPoint() {X=2f, Y=6f},
                new SKPoint() {X=2f, Y=7f},
                new SKPoint() {X=2f, Y=8f},
                new SKPoint() {X=2f, Y=9f},
                new SKPoint() {X=3f, Y=-10f},
                new SKPoint() {X=3f, Y=-9f},
                new SKPoint() {X=3f, Y=-8f},
                new SKPoint() {X=3f, Y=-7f},
                new SKPoint() {X=3f, Y=-6f},
                new SKPoint() {X=3f, Y=-5f},
                new SKPoint() {X=3f, Y=-4f},
                new SKPoint() {X=3f, Y=-3f},
                new SKPoint() {X=3f, Y=-2f},
                new SKPoint() {X=3f, Y=-1f},
                new SKPoint() {X=3f, Y=0f},
                new SKPoint() {X=3f, Y=1f},
                new SKPoint() {X=3f, Y=2f},
                new SKPoint() {X=3f, Y=3f},
                new SKPoint() {X=3f, Y=4f},
                new SKPoint() {X=3f, Y=5f},
                new SKPoint() {X=3f, Y=6f},
                new SKPoint() {X=3f, Y=7f},
                new SKPoint() {X=3f, Y=8f},
                new SKPoint() {X=3f, Y=9f},
                new SKPoint() {X=4f, Y=-9f},
                new SKPoint() {X=4f, Y=-8f},
                new SKPoint() {X=4f, Y=-7f},
                new SKPoint() {X=4f, Y=-6f},
                new SKPoint() {X=4f, Y=-5f},
                new SKPoint() {X=4f, Y=-4f},
                new SKPoint() {X=4f, Y=-3f},
                new SKPoint() {X=4f, Y=-2f},
                new SKPoint() {X=4f, Y=-1f},
                new SKPoint() {X=4f, Y=0f},
                new SKPoint() {X=4f, Y=1f},
                new SKPoint() {X=4f, Y=2f},
                new SKPoint() {X=4f, Y=3f},
                new SKPoint() {X=4f, Y=4f},
                new SKPoint() {X=4f, Y=5f},
                new SKPoint() {X=4f, Y=6f},
                new SKPoint() {X=4f, Y=7f},
                new SKPoint() {X=4f, Y=8f},
                new SKPoint() {X=5f, Y=-9f},
                new SKPoint() {X=5f, Y=-8f},
                new SKPoint() {X=5f, Y=-7f},
                new SKPoint() {X=5f, Y=-6f},
                new SKPoint() {X=5f, Y=-5f},
                new SKPoint() {X=5f, Y=-4f},
                new SKPoint() {X=5f, Y=-3f},
                new SKPoint() {X=5f, Y=-2f},
                new SKPoint() {X=5f, Y=-1f},
                new SKPoint() {X=5f, Y=0f},
                new SKPoint() {X=5f, Y=1f},
                new SKPoint() {X=5f, Y=2f},
                new SKPoint() {X=5f, Y=3f},
                new SKPoint() {X=5f, Y=4f},
                new SKPoint() {X=5f, Y=5f},
                new SKPoint() {X=5f, Y=6f},
                new SKPoint() {X=5f, Y=7f},
                new SKPoint() {X=6f, Y=-8f},
                new SKPoint() {X=6f, Y=-7f},
                new SKPoint() {X=6f, Y=-6f},
                new SKPoint() {X=6f, Y=-5f},
                new SKPoint() {X=6f, Y=-4f},
                new SKPoint() {X=6f, Y=-3f},
                new SKPoint() {X=6f, Y=-2f},
                new SKPoint() {X=6f, Y=-1f},
                new SKPoint() {X=6f, Y=0f},
                new SKPoint() {X=6f, Y=1f},
                new SKPoint() {X=6f, Y=2f},
                new SKPoint() {X=6f, Y=3f},
                new SKPoint() {X=6f, Y=4f},
                new SKPoint() {X=6f, Y=5f},
                new SKPoint() {X=6f, Y=6f},
                new SKPoint() {X=6f, Y=7f},
                new SKPoint() {X=7f, Y=-7f},
                new SKPoint() {X=7f, Y=-6f},
                new SKPoint() {X=7f, Y=-5f},
                new SKPoint() {X=7f, Y=-4f},
                new SKPoint() {X=7f, Y=-3f},
                new SKPoint() {X=7f, Y=-2f},
                new SKPoint() {X=7f, Y=-1f},
                new SKPoint() {X=7f, Y=0f},
                new SKPoint() {X=7f, Y=1f},
                new SKPoint() {X=7f, Y=2f},
                new SKPoint() {X=7f, Y=3f},
                new SKPoint() {X=7f, Y=4f},
                new SKPoint() {X=7f, Y=5f},
                new SKPoint() {X=7f, Y=6f},
                new SKPoint() {X=8f, Y=-6f},
                new SKPoint() {X=8f, Y=-5f},
                new SKPoint() {X=8f, Y=-4f},
                new SKPoint() {X=8f, Y=-3f},
                new SKPoint() {X=8f, Y=-2f},
                new SKPoint() {X=8f, Y=-1f},
                new SKPoint() {X=8f, Y=0f},
                new SKPoint() {X=8f, Y=1f},
                new SKPoint() {X=8f, Y=2f},
                new SKPoint() {X=8f, Y=3f},
                new SKPoint() {X=8f, Y=4f},
                new SKPoint() {X=8f, Y=5f},
                new SKPoint() {X=9f, Y=-5f},
                new SKPoint() {X=9f, Y=-4f},
                new SKPoint() {X=9f, Y=-3f},
                new SKPoint() {X=9f, Y=-2f},
                new SKPoint() {X=9f, Y=-1f},
                new SKPoint() {X=9f, Y=0f},
                new SKPoint() {X=9f, Y=1f},
                new SKPoint() {X=9f, Y=2f},
                new SKPoint() {X=9f, Y=3f},
                new SKPoint() {X=10f, Y=-3f},
                new SKPoint() {X=10f, Y=0f},
                new SKPoint() {X=9.950042f, Y=0.99833417f},
                new SKPoint() {X=9.800666f, Y=1.9866933f},
                new SKPoint() {X=9.553365f, Y=2.955202f},
                new SKPoint() {X=9.21061f, Y=3.8941834f},
                new SKPoint() {X=8.7758255f, Y=4.7942553f},
                new SKPoint() {X=8.253356f, Y=5.646425f},
                new SKPoint() {X=7.648422f, Y=6.442177f},
                new SKPoint() {X=6.9670672f, Y=7.173561f},
                new SKPoint() {X=6.2160997f, Y=7.833269f},
                new SKPoint() {X=5.4030232f, Y=8.41471f},
                new SKPoint() {X=4.535961f, Y=8.912073f},
                new SKPoint() {X=3.6235776f, Y=9.320391f},
                new SKPoint() {X=2.6749883f, Y=9.635582f},
                new SKPoint() {X=1.6996714f, Y=9.854497f},
                new SKPoint() {X=0.707372f, Y=9.97495f},
                new SKPoint() {X=-0.29199523f, Y=9.995736f},
                new SKPoint() {X=-1.288445f, Y=9.916648f},
                new SKPoint() {X=-2.272021f, Y=9.738477f},
                new SKPoint() {X=-3.2328956f, Y=9.463001f},
                new SKPoint() {X=-4.1614685f, Y=9.092975f},
                new SKPoint() {X=-5.048461f, Y=8.632093f},
                new SKPoint() {X=-5.885011f, Y=8.084964f},
                new SKPoint() {X=-6.6627603f, Y=7.457052f},
                new SKPoint() {X=-7.373937f, Y=6.754632f},
                new SKPoint() {X=-8.011436f, Y=5.9847217f},
                new SKPoint() {X=-8.568888f, Y=5.1550136f},
                new SKPoint() {X=-9.040722f, Y=4.273799f},
                new SKPoint() {X=-9.422223f, Y=3.3498814f},
                new SKPoint() {X=-9.709581f, Y=2.3924932f},
                new SKPoint() {X=-9.899925f, Y=1.4112f},
                new SKPoint() {X=-9.991351f, Y=0.41580662f},
                new SKPoint() {X=-9.982947f, Y=-0.5837414f},
                new SKPoint() {X=-9.874798f, Y=-1.577457f},
                new SKPoint() {X=-9.667982f, Y=-2.555411f},
                new SKPoint() {X=-9.364567f, Y=-3.5078323f},
                new SKPoint() {X=-8.967585f, Y=-4.4252043f},
                new SKPoint() {X=-8.481f, Y=-5.2983613f},
                new SKPoint() {X=-7.909677f, Y=-6.118579f},
                new SKPoint() {X=-7.259323f, Y=-6.8776617f},
                new SKPoint() {X=-6.536436f, Y=-7.568025f},
                new SKPoint() {X=-5.7482395f, Y=-8.182771f},
                new SKPoint() {X=-4.9026084f, Y=-8.715757f},
                new SKPoint() {X=-4.007992f, Y=-9.161659f},
                new SKPoint() {X=-3.0733287f, Y=-9.516021f},
                new SKPoint() {X=-2.107958f, Y=-9.775301f},
                new SKPoint() {X=-1.1215253f, Y=-9.93691f},
                new SKPoint() {X=-0.12388664f, Y=-9.999232f},
                new SKPoint() {X=0.8749898f, Y=-9.961646f},
                new SKPoint() {X=1.8651237f, Y=-9.824526f},
                new SKPoint() {X=2.8366218f, Y=-9.589243f},
                new SKPoint() {X=3.7797775f, Y=-9.258147f},
                new SKPoint() {X=4.685167f, Y=-8.834546f},
                new SKPoint() {X=5.543743f, Y=-8.322675f},
                new SKPoint() {X=6.3469286f, Y=-7.727645f},
                new SKPoint() {X=7.0866976f, Y=-7.055403f},
                new SKPoint() {X=7.7556586f, Y=-6.3126664f},
                new SKPoint() {X=8.347128f, Y=-5.5068555f},
                new SKPoint() {X=8.855195f, Y=-4.646022f},
                new SKPoint() {X=9.274784f, Y=-3.7387667f},
                new SKPoint() {X=9.601703f, Y=-2.794155f},
                new SKPoint() {X=9.8326845f, Y=-1.821625f},
                new SKPoint() {X=9.965421f, Y=-0.83089405f},
                new SKPoint() {X=9.998587f, Y=0.16813901f}
            };

            yield return new TestCaseData(10.0f, expected);
        }
    }
}